### ISSUE TITLE
Cannot import astrometry.util.util

### ISSUE THREAD

**Issue by gvnnlgl** [dstndstn/astrometry.net#199]
In a raspbian buster environment, I compiled 0.80 to default /usr/local/astrometry; all suggested libraries installed with apt. 
Solving and plotting ok with solve-field, but I would need to use the util in python.
util.py is giving error because _util is not found, although there is  _util.cpython-37m-arm-linux-gnueabihf.so file for it in /usr/local/astrometry/lib/python/astrometry/util
Is there something I need to do while making?

**Comment by dstndstn** [comment]
Hi,
Have you added to your PYTHONPATH?  eg,

export PYTHONPATH=${PYTHONPATH}:/usr/local/astrometry/lib/python

?  One additional note, you should *not* be in the astrometry/ source directory when you try to import, because there is an 'astrometry' symlink there that python will treat as the package.  So try,

export PYTHONPATH=${PYTHONPATH}:/usr/local/astrometry/lib/python
cd /tmp
python3 -c "import astrometry; print(astrometry.__file__); print(astrometry.__version__)"
python3 -c "import astrometry.util; print(astrometry.util.__file__)"
python3 -c "import astrometry.util.util; print(astrometry.util.util.__file__)"

thanks

**Comment by dstndstn** [comment]
ps, we have an ubuntu 18 build in our CI, if that's of any help.
https://app.circleci.com/pipelines/github/dstndstn/astrometry.net?branch=master

**Comment by gvnnlgl** [comment]
Thanks for quick reply! Here is result of proposed test, if it looks ok I will try later if this can solve the issue

...:$ python3 -c "import astrometry; print(astrometry.__file__); print(astrometry.__version__)"
/usr/local/astrometry/lib/python/astrometry/__init__.py
0.80

...:$ python3 -c "import astrometry.util; print(astrometry.util.__file__)"
/usr/local/astrometry/lib/python/astrometry/util/__init__.py

...:$ python3 -c "import astrometry.util.util; print(astrometry.util.util.__file__)"
/usr/local/astrometry/lib/python/astrometry/util/util.py

**Comment by gvnnlgl** [comment]
(of course by replacing bold font with double underscores)

**Comment by gvnnlgl** [comment]
Thanks for your time, I noted that in your test snippet you used python3 and I questioned myself about the version my system was using by default: in fact it was 2.7! So I started my webapp (made in flask) by using python3 command and now it is importing astrometry.util.util... In closing the issue, I report the result of test snippet with "python" instead of "python3" if it may be useful for others:

...:$ python -c "import astrometry.util.util; print(astrometry.util.util.__file__)"
ImportError: /usr/local/astrometry/lib/python/astrometry/util/_util.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: PyBytes_AsStringAndSize

**Comment by dstndstn** [comment]
Aha!  Good sleuthing.  Thanks for leaving answers for the future 👍
