### ISSUE TITLE
fitsio.h not found during make of -0.50

### ISSUE THREAD

**Issue by DougWelch** [dstndstn/astrometry.net#2]
Hi Dustin et al, 

It looks like fitsio.h used to be in one of the sub-directories blind, cfitsio, or util (or possibly I just copied it there in the past!) In any case, it isn't being found naturally.

Cheers,
Doug

root@cepheid2:/usr/local/src/astrometry.net-0.50# make
make -C qfits-an
make[1]: Entering directory `/1/local/src/astrometry.net-0.50/qfits-an'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/1/local/src/astrometry.net-0.50/qfits-an'
make -C gsl-an
make[1]: Entering directory`/1/local/src/astrometry.net-0.50/gsl-an'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory`/1/local/src/astrometry.net-0.50/gsl-an'
make -C util
make[1]: Entering directory `/1/local/src/astrometry.net-0.50/util'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/1/local/src/astrometry.net-0.50/util'
make -C catalogs
make[1]: Entering directory`/1/local/src/astrometry.net-0.50/catalogs'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory`/1/local/src/astrometry.net-0.50/catalogs'
make -C libkd
make[1]: Entering directory `/1/local/src/astrometry.net-0.50/libkd'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/1/local/src/astrometry.net-0.50/libkd'
make -C blind
make[1]: Entering directory`/1/local/src/astrometry.net-0.50/blind'
gcc  -g -Wall -ffinite-math-only -fno-signaling-nans -pthread -march=native -O3 -fomit-frame-pointer -DNDEBUG -fpic -Winline -I../include -I../include/astrometry -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -I../catalogs         -I../include -I../include/astrometry -I../gsl-an     -I../include -I../include/astrometry -I../gsl-an  -I../util -I.  -I/usr/include/cairo -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng12     -c -o image2xy-files.o image2xy-files.c
image2xy-files.c:32:20: fatal error: fitsio.h: No such file or directory
compilation terminated.
make[1]: **\* [image2xy-files.o] Error 1
make[1]: Leaving directory `/1/local/src/astrometry.net-0.50/blind'
make: **\* [subdirs] Error 2

**Comment by knyland** [comment]
Hi Dustin,

The original person asking this question appears to not have responded, but I am having the same problem, and the solution in the link you provided unfortunately does not solve the issue for me.  

I'm having essentially the same problem on mac os 10.10 and on my Red Hat Linux Workstation.  Something seems to be going wrong with my cfitsio installation (or perhaps I'm simply not installing it in a clever enough location, or appropriately linking libraries . . . . ).  Do you have any additional advice?

Thanks!!!!
~Kristina

**Comment by knyland** [comment]
(I should note that my ultimate goal is to get Tractor working, but obviously the astrometry.net installation needs to be fixed first . . . . )

**Comment by dstndstn** [comment]
Hi,

Sorry for my delay -- could you please elaborate on what you have tried and what result you get?

What should be the easiest way is to get pkg-config to do its job.  cfitsio should have installed a file

lib/pkgconfig/cfitsio.pc

and if cfitsio is not installed in a standard place, you need to tell pkg-config about it, via

export PKG_CONFIG_PATH=/path/to/cfitsio/lib/pkgconfig

You can test whether it is working by

pkg-config --cflags cfitsio
pkg-config --libs cfitsio

and then re-make the Astrometry.net code.

On Mac OSX, you can install it using Homebrew... it's in the homebrew-science tap.

cheers,
--dustin

**Comment by knyland** [comment]
Hi Dustin,

Thanks so much for getting back to me!

I managed to somehow get everything installed after re-installing my OS
and leaving the default Python installation pristine (I previously had
Canopy, Anaconda, Homebrew, Fink, MacPorts - it was a garbled mess of
symlinks that was indecipherable).

I actually have a different question right now . . . . about Tractor.  I'm
going through some example scripts sent to me by a collaborator, and I've
discovered that certain classes/functions that work for my collaborator
(who downloaded Tractor some time ago . . . ) do not work for me.  Perhaps
there has been some re-naming of classes/functions at some point?  The
item in question at the moment is tractor.FitsWcs.  The FitsWcs class is
not defined in basics.py, but other similarly named classes are defined,
for instance, ConstantFitsWcs (does this have the same functionality as
FitsWcs did previously?).  Sorry I'm so confused - I've never used the
software before, and I'm new to optical/infrared data (I'm usually a radio
astronomer!).

Thanks!  :)

~Kristina

> Hi,
>
> Sorry for my delay -- could you please elaborate on what you have tried
> and what result you get?
>
> What should be the easiest way is to get pkg-config to do its job.
> cfitsio should have installed a file
>
> lib/pkgconfig/cfitsio.pc
>
> and if cfitsio is not installed in a standard place, you need to tell
> pkg-config about it, via
>
> export PKG_CONFIG_PATH=/path/to/cfitsio/lib/pkgconfig
>
> You can test whether it is working by
>
> pkg-config --cflags cfitsio
> pkg-config --libs cfitsio
>
> and then re-make the Astrometry.net code.
>
> On Mac OSX, you can install it using Homebrew... it's in the
> homebrew-science tap.
>
> cheers,
> --dustin
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dstndstn/astrometry.net/issues/2#issuecomment-159045829


~~~~~~~~~~~~~~~~~~~~~~
Dr. Kristina Nyland
Postdoctoral Researcher
NRAO
520 Edgemont Rd.
Charlottesville, VA 22903
~~~~~~~~~~~~~~~~~~~~~~

**Comment by dstndstn** [comment]
Exactly as you've figured out, FitsWcs got renamed to ConstantFitsWcs.
(Nice sleuthing!)  Apologies for the near complete lack of
documentation...  Please feel free to continue sending me more questions as
you get set up, either at the Tractor repo (
https://github.com/dstndstn/tractor) or direct by email.

**Comment by knyland** [comment]
Hi Dustin,

Thanks again for your reply!  I think the situation may be a bit more
complicated, replacing FitsWcs with ConstantFitsWcs in my sample code I'm
trying to run does not seem to solve some of the issues I'm having.

For instance, my collab had the following:

kswcs=FitsWcs(Tan('xmm_tile3_ks_20141017.fits',1))
.
.
.
t=Tan()
t.set_cd(kswcs.cd1_1,kswcs.cd2_1,kswcs.cd1_2,kswcs.cd2_2)
.
.
.

If FitsWcs and ConstantFitsWcs have exactly the same functionality, then
replacing FitsWcs with ConstantFitsWcs should work just fine here.  But,
after making this change in the latest Tractor version, t.set_cd fails
because kswcs does not have attributes cd1_1, etc.  However, replacing
FitsWcs with TanWcs seems to do the trick (though I don't understand why).

I know I can get the CD matrix values cd1_1, etc., from the image header,
but this is making me wonder: have there been other changes I'm not aware
of yet that might have more significant implications?  Since I don't know
what I'm doing at all, I'm trying to learn from the example scripts I've
been given.

Could you clarify how the functionality of FitsWcs in older software
versions is obtained in the latest version of Tractor in a bit more
detail?  Also, I'm a bit confused about why/when I would want to use
TanWcs(Tan(file, ext)) and when I might want to use the equivalent of
FitsWcs(Tan(file,ext)) in the new software version (unless these syntaxes
did/do the same thing?).

Sorry to be a pest!  I really appreciate your help with this!!!!

Thanks,
~Kristina




> Exactly as you've figured out, FitsWcs got renamed to ConstantFitsWcs.
> (Nice sleuthing!)  Apologies for the near complete lack of
> documentation...  Please feel free to continue sending me more questions
> as
> you get set up, either at the Tractor repo (
> https://github.com/dstndstn/tractor) or direct by email.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/dstndstn/astrometry.net/issues/2#issuecomment-159122223


~~~~~~~~~~~~~~~~~~~~~~
Dr. Kristina Nyland
Postdoctoral Researcher
NRAO
520 Edgemont Rd.
Charlottesville, VA 22903
~~~~~~~~~~~~~~~~~~~~~~

**Comment by dstndstn** [comment]
I'm going to try to answer this in the Tractor repo: https://github.com/dstndstn/tractor/issues/72
thanks
