### ISSUE TITLE
libkd/an-fls.h licensed as GPL v2

### ISSUE THREAD

**Issue by rikmills** [dstndstn/astrometry.net#212]
This has caused the rejection of the stellarsolver source from Debian which incorporates libkd from astrometry.

https://lists.debian.org/debian-qt-kde/2021/02/msg00114.html

> in this package there are files under the GPL-2 (stellarsolver/astrometry/libkd/an-fls.h) mixed with files under GPL-3+.
> According to [1] this is not allowed.
> 
>   Thorsten
> 
> [1] https://www.gnu.org/licenses/gpl-faq.en.html#AllCompatibility

See: https://github.com/rlancaste/stellarsolver/issues/76

**Comment by dstndstn** [comment]
If you want to contribute a clean-room replacement licensed in BSD-3, go ahead.

The required function signature is simple:

/**
 * fls - find last (most-significant) bit set
 * Eg, fls(0) = 0, fls(1) = 1, fls(0x80000000) = 32.
 */
static inline int an_fls(int x);

cheers,
--dustin

**Comment by rlancaste** [comment]
Isn't this a problem for astrometry.net as well since I think from what I just saw in looking at the code, the code was taken from the linux kernel which according to this is distributed under GPL V2 while astrometry.net is licensed under GPL V3.  So I think it affects more than just my project.

**Comment by dstndstn** [comment]
Uh, yes, you're correct.

**Comment by dstndstn** [comment]
I just updated our LICENSE statement to reflect this.

**Comment by pinotree** [comment]
Just to make things a bit more explicitl:
- `libkd/an-fls.h` is GPL v2 (only)
- `include/astrometry/ctmf.h` and `util/ctmf.c` are GPL 3+

IANAL: even ignoring the majority of the files (that are licensed as BSD), to me this means that the resulting binary cannot be distributed, as there is no "intersection" in the allowed licenses.

**Comment by dstndstn** [comment]
<img width="787" alt="1" src="https://user-images.githubusercontent.com/1065981/107779021-ceb8f980-6d12-11eb-8b2a-34156c5e838a.png">

If I'm not mistaken, we are in row 2, column 2, which is OK*.

**Comment by dstndstn** [comment]
Regardless, in e1b21dcf14d86f0f40bf1052011f89a0697c9541 I swapped in the FreeBSD version of this function, and in later commits updated the license statement.

**Comment by dstndstn** [comment]
@rikmills , please let me know if you'd like me to a cut a new release with this change, for checking with Debian.

**Comment by rikmills** [comment]
> @rikmills , please let me know if you'd like me to a cut a new release with this change, for checking with Debian.

Well, @pinotree is the actual Debian developer here who had stellarsolver rejected, so I defer to his opinion is he is willing to give it.

**Comment by rlancaste** [comment]
Thank you very much Dustin for addressing the issue so quickly!!  I am sorry I wasn't able to be much help, since I have been extremely busy with my real job the last month or so.  Hybrid teaching has taken a whole lot of work on my part, so I haven't had as much time for my astronomy and coding hobbies.  I will update the copy of this file in the StellarSolver repo this weekend.  

Just a note though, if I am understanding this issue completely, this means that any astronomy program that has bundled a binary version of astrometry.net or a binary version of any astrometry.net derivative based on the code before this update will also have a serious license issue and should be updated to include this change.  That would probably affect a number of programs over the last few years.  Although if they just distributed the source code and the users built the binaries on their own system and didn't distribute the binaries they built, that would be fine.  Would that be correct?

**Comment by dstndstn** [comment]
I'm afraid I do not know any of the legalities of distributing binaries -- I never do that so it's just not in my wheelhouse.

**Comment by rlancaste** [comment]
Thats not a problem, and I don't think that is your responsibility by any means, you do tons of great work with creating, maintaining and improving astrometry.net.  I was just asking mainly to get clarification from any of the posters in this thread since we might want to let some folks know they need to update.  

I can take care of StellarSolver and KStars.   I can also inform Jasem about it so he can take care of anything he might have control over in INDI, his PPA, or other open source locations.  I can also let Cloudmakers know about it so they can update the Mac Astrometry program.  But I know astrometry.net binaries have been distributed for years in homebrew and in the package distributions systems of various Linux based systems's like Ubuntu and Arch Linux.  If I understand this right, they should be informed they need to update.  There is also the Cygwin based ANSVR.  And I don't know what other programs on Windows bundle an astrometry solver inside.  Jasem might know who to tell.  I can do my best to get the word out if this is needed.

**Comment by rikmills** [comment]
Debian bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=983306
