### ISSUE TITLE
<base>-ngc.png does not show any annotations 

### ISSUE THREAD

**Issue by harpreps** [dstndstn/astrometry.net#225]
Hello Dustin,
I have been using Nova for solving images. But I now installed the local version on my ubuntu using the apt-get command. I got all 42xx and 41xx index files. 
The images solve accurately but I see that the <base>-ngc.png file does not show any annotations. I see references to 200 index files which are not available any more. But you also mentioned elsewhere that the 4200 index files were 'better' for solve. Do these index files have info missing that is causing the annotation to not show up? I used the plotann.py too. Same result.
Any way that I can get the annotations part working? Thanks in advance.
Regards,
Harry

**Comment by dstndstn** [comment]
Hi,

The index files you use have no effect on the annotations; the annotated objects come from different catalogs.

Some Ubuntu-distributed versions omit the NGC/IC catalogs because of licensing issues, so that might be the issue.

Otherwise, if you want Henry Draper, Hipparcos, or Tycho-2 stars annotated, you'll have to grab the relevant data files from http://data.astrometry.net/

cheers,
--dustin

**Comment by harpreps** [comment]
Got it.
So if I install from the github code, should this be fixed? Or will I still need to grab the relevant catalogs for NGC/IC objects? If so, can you point me to those? 

Appreciate the help,
Harry.

**Comment by dstndstn** [comment]
Github version has the NGC/IC versions included.

**Comment by harpreps** [comment]
That worked like expected on test images. 
Thanks again,
Harry
