### ISSUE TITLE
`backend` in `testscript-astro`

### ISSUE THREAD

**Issue by grapeot** [dstndstn/astrometry.net#283]
In [the document](http://astrometry.net/doc/nova.html) that discusses how to deploy a local instance of astrometry.net, it's mentioned that the backbone of the computation server is the `testscript-astro` script. [This script](https://github.com/dstndstn/astrometry.net/blob/main/net/testscript-astro) essentially calls an executable named `backend`. However, I'm having trouble locating this file in both the source code and the compiled executables. Could you provide more details about this file? Thanks a lot!

**Comment by dstndstn** [comment]
ugh, that documentation is all pretty old.  'backend' is renamed to 'astrometry-engine' (engine-main.c).

**Comment by grapeot** [comment]
Ah I see. Thanks for the reply! While I’m happy to refine the doc, just curious shall I still use “testscript-astro” to process the data on the compute server? It (the code, not the document) seems outdated because it’s still referring the backend as “backend” instead of “astrometry-engine”. While I can help submit a PR to fix it and the doc, wanted to first get some guidance on the direction to make sure it makes sense to fix this file.

**Comment by dstndstn** [comment]
Good question.  So, the current `nova.astrometrynet` setup is a little different than described there, because we do everything on the same machine.

* `https://github.com/dstndstn/astrometry.net/blob/main/net/nova-jobs.service` is copied to `/etc/systemd/system` and enabled and run through `service nova-jobs start` etc.  As you can see, it has some paths hard-coded.
* `https://github.com/dstndstn/astrometry.net/blob/main/net/nova-uwsgi.service` is the service that runs the uWSGI server (Python/Django backend for the web service).
* we run a standard Postgres install for the database.  Database account/setup instructions would be useful...
* we run Apache2 as the web front-end -- I could add this config file to the repo...

**Comment by grapeot** [comment]
This is super helpful! I was also thinking about making it work on the same machine and putting it behind some production ready process managers (such as uWSGI) and web servers (such as apache) and it seems it’s already done so it’s mostly probably some documentation work. Let me dig deeper into that and figure out a plan. Thanks for the guidance!

**Comment by dstndstn** [comment]
Okay, so apache2 config (in sites-available) is a bit complicated because of supporting SSL, but ignoring that, it's roughly
```
ServerName nova.astrometry.net

Alias /static/ /home/nova/astrometry/net/static/

<Directory /home/nova/astrometry/net/static>
Require all granted
</Directory>

ProxyPass /static !

ProxyPass / uwsgi://localhost:3030/
ProxyPassReverse / uwsgi://localhost:3030/

RewriteEngine on
```

**Comment by grapeot** [comment]
Thanks for all the info Dustin! I updated [the PR](https://github.com/dstndstn/astrometry.net/pull/282) according to your suggestions, and made it work! Also updated the documents. I still need to figure out more details on the DB and reverse proxy. Plan to submit another PR for that. The current PR is ready for review now.
