### ISSUE TITLE
Question: parallel plate solving

### ISSUE THREAD

**Issue by bmorris3** [dstndstn/astrometry.net#69]
When running two `solve-field` commands from the same machine in different shells, I've found that one or the other will fail to read the index files. Does each call to `solve-field` keep an open file stream for the index files? And therefore should `solve-field` only be called serially?

Thanks!

**Comment by dstndstn** [comment]
That's strange, I've never seen or heard of anything like that before.  The nova.astrometry.net web site runs up to 16 jobs in parallel on our compute machine and we've never seen that.

How are they failing?  Could you send full logs (maybe with "solve-field -v" for more verboseness)?

Solve-field opens the index files read-only and non-exclusive, so there shouldn't be any conflicts between processes.  It uses mmap() to memory-map the files so that they are read in as necessary.  This does reserve *memory space*, but that's normally only an issue on 32-bit machines.

**Comment by bmorris3** [comment]
I must have been keying something wrong last night -- I can't reproduce my example that had the issue. Nevermind! Sorry to bother you again. Learning is hard. :+1:

**Comment by dstndstn** [comment]
:)
