### ISSUE TITLE
Discard saturated stars

### ISSUE THREAD

**Issue by 4ks1** [dstndstn/astrometry.net#72]
As saturated stars degrade the accuracy of the solution, maybe they could be excluded during source extraction?

A simple way could be to allow the user to define a threshold in ADU via a command line parameter that safely marks saturated pixels in the respective image(s). In this way, every detected source that contains a pixel with a value higher than this threshold could be discarded.

Would be useful :-).

**Comment by dstndstn** [comment]
No, because the brightest stars are preferentially selected to be in the index files and to form the quadrangle features we use to match the image.  Omitting the saturated (brightest) stars could mean eliminating all of the stars that are in common between the image and the index.

Generally speaking, the downsampling and smoothing before source detection tends to work to produce reasonable detections and centroids for saturated stars.
