### ISSUE TITLE
Path problems with image2pnm.py and removelines.py

### ISSUE THREAD

**Issue by dmopalmer** [dstndstn/astrometry.net#93]
Commit     4c6b74e  commented out some path manipulation that was required if the astrometry module wasn't in the path.  As a result, image2pnm.py and removelines.py can no longer load the astrometry utilities they rely on.

The commented code doesn't work due to relative imports not working unless running as a module.  The following code is an ugly reasonable work-around replacement.
```
if __name__ == '__main__':
    sys.path.append(os.path.dirname(
                    os.path.dirname(
                    os.path.dirname(
                    os.path.realpath(__file__)))))
    pass
```

**Comment by dstndstn** [comment]
Hi,
Thanks for this report, and sorry for my slow response.  I just pushed a set of commits to master that may address this -- could you please test them in your setup?
thanks,
--dustin

**Comment by dmopalmer** [comment]
This seems to work.

It does not cover the edge-case where somebody changes directory to /usr/local/astrometry/bin and then runs ./image2pnm 

Also, it uses /usr/bin/env python instead of the python passed to the makefile.  (On my system, I have the python built in to OSX, the macports python, and anaconda python for the default and in various virtual environments, each of which comes in python2 and python3 varieties.  To run solve-field I use a wrapper that sets up the python and path to specific values and then runs /usr/local/astrometry/bin/solve-field .)

**Comment by dstndstn** [comment]
Ugh, I really don't want to bake into the scripts the python passed to the Makefile during install...  If you're inside a virtualenv, aren't the paths set up so that /usr/bin/env does the right thing?  I would think that if you need to run a specific version of python, then there's not much choice but to set up environment variables so that solve-field knows what to run... no?

Thanks for the testing, and good catch with the ./image2pnm .  Could I ask you to test another version?  It's in the 'relpath' branch -- I only changed the image2pnm script, trying:
```
    sys.path.insert(1, os.path.normpath(os.path.join(os.path.dirname(__file__), '..', 'lib', 'python')))
```

**Comment by knro** [comment]
Not sure if this is related, but just installed astrometry.net from GIT and got this:

jasem@sps:~/Projects/development/astrometry.net$ /usr/bin/solve-field --no-verify --no-plots --resort --downsample 2 -O -L 19.3223 -H 26.6952 -u aw -3 263.683 -4 -37.1131 -5 30 --parity neg -W /tmp/solution.wcs /tmp/fitsK19661
Reading input file 1 of 1: "/tmp/fitsK19661"...
Usage: image2pnm [options]

image2pnm: error: no such option: --mydir
augment-xylist.c:589:backtick Failed to run command: /usr/bin/image2pnm --infile /tmp/fitsK19661 --uncompressed-outfile /tmp/tmp.uncompressed.Grjkef --outfile /tmp/tmp.ppm.lQpnDp --ppm --mydir /usr/bin/solve-field
 ioutils.c:567:run_command_get_outputs Command failed: return value 2

**Comment by dstndstn** [comment]
Hi,

Is there any chance you have an older version of the image2pnm.py script somewhere?  Perhaps on your PYTHONPATH?

(if you do:
python -c "from astrometry.util import image2pnm; print image2pnm.__file__"
does it show anything?)

thanks,
--dstn

**Comment by mariavd** [comment]
Hello,

I am having the same problem. At the moment I have astrometry compiled to /usr/local/astrometry/ and one more installed with apt-get. Maybe this is the reason.

This is the output of python -c "from astrometry.util import image2pnm; print image2pnm.file"

Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from astrometry.util import image2pnm
>>> print  image2pnm.file
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'file'
>>> 

Thank you.

**Comment by dstndstn** [comment]
Oh, oops, it should be
```
python -c "from astrometry.util import image2pnm; print image2pnm.__file__"
```
with two underscores around the 'file'.  That prints where the module 'image2pnm' was found by python.  If it's the one in /usr/local/astrometry, then that's good...

thanks,
--dustin

**Comment by mariavd** [comment]
Thank you, Dustin. I compiled the source again and after exporting the PYTHONPATH the binary solve-field runs properly.

**Comment by llimonta** [comment]
Sorry to resume this from the death, what if by doing this 'python -c "from astrometry.util import image2pnm; print image2pnm.__file__" ' we don't get the file from usr/local/astrometry?

**Comment by dstndstn** [comment]
You're going to have to give more details than that.... you get a version from somewhere else?  Do you have the PYTHONPATH variable set?

**Comment by llimonta** [comment]
Hi Dustin, thanks for the insanely fast response.  Apologies if I won't sound very technical but I am not too familiar with Ubuntu - I use it only when I need to code and don't do much else with it.
There's a good chance I have created somewhat of a mess, as I used to have installed the .50 version, un-installed it because apparently wasn't working anymore and have tried both manual installation for the latest release and sudo-apt get install. 

For the manual situation, when I do echo $PYTHONPATH  it doesn't give me anything. Where should I set it to? /usr/local/astrometry/bin ?  When comparing to the .63 version I have on another laptop, it gives me the same empty location

This is the output when I try to run solve-field:

solve-field AzDecImages/Frame320000Day31032014.fits
Reading input file 1 of 1: "AzDecImages/Frame320000Day31032014.fits"...
Traceback (most recent call last):
  File "/usr/local/astrometry/bin/image2pnm", line 14, in <module>
    from astrometry.util.image2pnm import main
ImportError: No module named util.image2pnm
augment-xylist.c:589:backtick Failed to run command: /usr/local/astrometry/bin/image2pnm --infile AzDecImages/Frame320000Day31032014.fits --uncompressed-outfile /tmp/tmp.uncompressed.6t90JT --outfile /tmp/tmp.ppm.eYeN9s --ppm --mydir /usr/local/astrometry/bin/solve-field
 ioutils.c:567:run_command_get_outputs Command failed: return value 1

**Comment by dstndstn** [comment]
Hi,
An empty $PYTHONPATH is fine.

The Debian/Ubuntu package really ought to just work, and probably gets installed in /usr rather than the version that seems to be complaining here, which is in /usr/local/astrometry...

Could you try running this and see what it says (it will probably fail at some point):

python -c "import os; import sys; sys.path.insert(1, os.path.normpath(os.path.join(os.path.dirname('/usr/local/astrometry/bin/image2pnm'), '..', 'lib', 'python'))); print(sys.path); import astrometry; print(astrometry.__file__); import astrometry.util; print(astrometry.util.__file__); import astrometry.util.image2pnm; print(astrometry.util.image2pnm.__file__)"

One hack you could try would be to set
export PYTHONPATH=/usr/local/astrometry/lib/python
to tell python where to find the code.  The bin/image2pnm script is supposed to do that, but it doesn't seem to be doing that correctly here.

cheers,
--dustin

**Comment by llimonta** [comment]
The workaround seems to work (I get another error regarding the CFITSIO library I am using) 

This is the output I get from the python -c command:

['', '/usr/local/astrometry/lib/python', '/usr/local/astrometry/lib/python', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/gtk-2.0']
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'file'

**Comment by llimonta** [comment]
It finally works!

Thanks a lot!!!
